export default [
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/lokesh_coder/128.jpg',
    name: 'Chandler Jacobi',
    job: 'Direct Security Executive',
    amount: 989.4,
    status: 'primary',
    date: 'Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg',
    name: 'Monserrat Marquardt',
    job: 'Forward Accountability Producer',
    amount: 471.44,
    status: 'danger',
    date: 'Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/supjoey/128.jpg',
    name: 'Lonie Wyman',
    job: 'Legacy Program Director',
    amount: 934.24,
    status: 'success',
    date: 'Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/holdenweb/128.jpg',
    name: 'Corine Abernathy',
    job: 'Chief Factors Planner',
    amount: 351.28,
    status: 'warning',
    date: 'Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/mikebeecham/128.jpg',
    name: 'Lorenz Botsford',
    job: 'Central Accountability Developer',
    amount: 355.3,
    status: 'neutral',
    date: 'Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/akmur/128.jpg',
    name: 'Everette Botsford',
    job: 'Product Group Architect',
    amount: 525.42,
    status: 'success',
    date: 'Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/nateschulte/128.jpg',
    name: 'Marilou Beahan',
    job: 'Future Security Planner',
    amount: 414.99,
    status: 'success',
    date: 'Mon Oct 28 2019 14:44:31 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jerrybai1907/128.jpg',
    name: 'Ceasar Sauer',
    job: 'Direct Brand Specialist',
    amount: 488.0,
    status: 'primary',
    date: 'Tue Jul 23 2019 00:24:44 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/igorgarybaldi/128.jpg',
    name: 'Rae McDermott',
    job: 'Lead Branding Engineer',
    amount: 502.69,
    status: 'danger',
    date: 'Sat Feb 01 2020 12:57:03 GMT-0300 (Brasilia Standard Time)',
  },
]
